# Generated by Django 3.0.3 on 2020-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200225_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=3),
        ),
    ]
