# Generated by Django 3.0.3 on 2020-02-26 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200225_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
    ]
